### ISSUE TITLE
Why you created ~~BaseType.hpp?

### ISSUE THREAD

**Issue by schzna** [azaika/wawl#1]
I think the integrate one is more better.

**Comment by azaika** [comment]
WinAPI often has strange design, so we sometimes should use some type for functions which belong other group.
In such time, integrated headers have too many functions. I think it isn't good.
(Sorry for my poor english)

**Comment by schzna** [comment]
I think so be better to integrate one and to use namespaces.
If you do what I said  ,you need not  divide file into ~~BaseType.hpp.
(sorry my English is poor ,too.)

**Comment by azaika** [comment]
@yuki74w 
using namespace is not solution of it, and I don't dislike deviding files.

**Comment by schzna** [comment]
@azaika 
no using namespace.  
example: BaseType.hpp

```
namespace wawl{
  namespace Icon{
    struct OEMIcon {
       //something data
    }
  }
}
```

**Comment by azaika** [comment]
BaseType.hpp is a header which defines type all wawl's header need.
I don't need chaos header.

**Comment by schzna** [comment]
I got it(you're thinking that IconBaseType.hpp is chaos...)

**Comment by azaika** [comment]
BaseType.hpp I said is only "BaseType.hpp", not includes ~~BaseType.hpp.
